### PR TITLE
Updated yargs-parer

### PR DESCRIPTION
**Pull request by Miniland1333**
Addresses GHSA-p9pc-299p-vxgp known vulnerability. All tests still pass!

### CODE REVIEW

**Comment by Miniland1333** [comment]
Also, I would recommend turning on Github's dependabot so that it can handle keeping these repository dependencies up to date for you!

**Comment by Miniland1333** [comment]
Closes https://github.com/DiegoZoracKy/convert-excel-to-json/issues/45

**Comment by Miniland1333** [comment]
@DiegoZoracKy since the tests all still pass is there anything else I need to do for this PR? It is just a npm update for the dependencies to remove the security vulnerability.

**Comment by DiegoZoracKy** [comment]
Hi @Miniland1333, it's merged now. I was on vacation, sorry. Thanks for your PR!

**Comment by DiegoZoracKy** [comment]
@Miniland1333 would you mind bumping the "patch" (https://semver.org/) on the package's version.

**Comment by Miniland1333** [comment]
I will open a new PR momentarily with the change. I do have a quick question @DiegoZoracKy: It looks like [I added a Github Action for testing to my fork](https://github.com/Miniland1333/cliss/blob/master/.github/workflows/node.js.yml), do you want me to remove this from the branch before submitting the PR or are you okay with it?

**Comment by Miniland1333** [comment]
Also, it looks like the side-effect of upgrading to a supported version of Mocha is that testing is no longer supported on NodeJS v8.0 due to lack of async/await https://travis-ci.org/github/DiegoZoracKy/cliss.

**Pull request merged**
